version: "3.8"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    networks:
      - traefik_default
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_default
    ports:
      - "80:80"
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    networks:
      - traefik_default
    deploy:
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role == worker
      labels:
        # traefik.enable=true and constraint label are needed because
        # of the restrictions we enforced in our traefik configuration
        - traefik.docker.network=traefik_default
        - traefik.enable=true
        - traefik.http.services.whoami.loadbalancer.server.port=80
        - "traefik.http.routers.whoami.rule=Host(`13.229.52.61`)"
        - "traefik.http.routers.whoami.entrypoints=web"

networks:
  traefik_default:
    external: true
